apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubessh.fullname" . }}
  labels:
    {{- include "kubessh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
      {{- if and .Values.service.nodePort (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "kubessh.selectorLabels" . | nindent 4 }}
